### ISSUE TITLE
[Header] - Add dark mode button to the header

### ISSUE THREAD

**Issue by david-at-greymass** [wharfkit/website#105]
Let's try placing the Dark mode switch to the header, next to the Github button, as it's easy to miss it in the footer

**Comment by david-at-greymass** [comment]
Fix here: https://github.com/wharfkit/website/pull/110

**Comment by david-at-greymass** [comment]
@Goodbyehorses can you mockup a design for this please

**Comment by Goodbyehorses** [comment]
Updated menu with dark mode switch in header:
![Menu mobile v3](https://github.com/wharfkit/website/assets/216542/712297f2-530a-4e0f-8b24-4a32f70505dc)
![Menu v2](https://github.com/wharfkit/website/assets/216542/af6eee0e-852c-4c56-8f64-025e9df6d2c1)
Animation example:
https://github.com/wharfkit/website/assets/216542/27a2f8d5-f5e6-4e92-b31d-97df9674bc0b
