### ISSUE TITLE
Prevent website tracker code from triggering except in production

### ISSUE THREAD

**Issue by aaroncox** [wharfkit/website#106]
The website tracking code to stats.greymass.com triggers on dev page load and in the dev preview builds. If we want accurate analytics to not be mixed up with the constant refreshing of our development builds, we should make it so that the tracking code is only triggered if its running on the live production website. 

Maybe this can be done if we detect the domain is wharfkit.com or something? 🤔

**Comment by david-at-greymass** [comment]
we use Vite, it exposes environment vars for that, more [HERE](https://vitejs.dev/guide/env-and-mode.html)
the base_url is exposed through the same object, so also can be used
