### ISSUE TITLE
Back to top button on website

### ISSUE THREAD

**Issue by david-at-greymass** [wharfkit/website#130]
We need a back to top button with a smooth scroll. The button could appear after 1-1.5 scrolled screens, or when user starts scrolling up.

We'll need the design from @Goodbyehorses

**Comment by Goodbyehorses** [comment]
![screenshot 1692188073](https://github.com/wharfkit/website/assets/216542/a212bbcd-f1df-4cfe-9fc2-5134a3ecca80)

**Comment by deansallinen** [comment]
Styles updated in 999a54313d0f2d03033b7f2f8897052e58800a67
