### ISSUE TITLE
ContractKit landing page GIF that highlights the feature of Wharf

### ISSUE THREAD

**Issue by david-at-greymass** [wharfkit/website#131]
Max needs to design an animation to highlight the features of the CK. Potential ideas: writing code with autocompletion popping up

https://t.me/wharfkit/978

**Comment by david-at-greymass** [comment]
Side by side concepts


![Image](https://github.com/wharfkit/website/assets/139813631/9c8d316f-3e4a-4d91-97d5-e1142786fb18)



![Image](https://github.com/wharfkit/website/assets/139813631/ed25bc8a-7025-4ee7-a376-89f3e0b644a3)

Those two images are the same size
They’re a bit tall - but I wanted to give it some breathing room.
I suppose I could potentially cut down the left one to only have the relevant code, like below, and shrink the animated code window too:



![Image](https://github.com/wharfkit/website/assets/139813631/97610c01-0ad9-42a6-a41c-862804370654)

**Comment by deansallinen** [comment]
Closed with: [4412db2](https://github.com/wharfkit/website/commit/4412db2d9155ecf9aee552344cbb0ca90b1a8c7b)
