### ISSUE TITLE
[Blog hero] - Minimize and add post description

### ISSUE THREAD

**Issue by david-at-greymass** [wharfkit/website#165]

**Comment by david-at-greymass** [comment]
**Story Points: 1**
  [See the discussion](https://action.parabol.co/meet/q2AH7Mz0di/estimate/2) in Sprint Poker #​​2

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by deansallinen** [comment]
Fixed in 02808a1d4110de4332f8030e84df0a8edc5ccea5
