### ISSUE TITLE
[Wharf homepage] - Swap CTA

### ISSUE THREAD

**Issue by david-at-greymass** [wharfkit/website#178]
From Mara: I have a note that we need to swap the “Looking to build a smart contract?” CTA on the Wharf homepage for the “Want to keep up with the latest Wharf developments?” CTA at the bottom. Then at the bottom, let’s put a CTA to the docs that says “Ready to dive in? Wharf’s docs have everything you need to start building. [Go to Documentation]”

**Comment by deansallinen** [comment]
Updated in f68d8261433d60c83b845edd18bbb2fdce20d945
