### ISSUE TITLE
Feature: Add "Edit this page" to documentation

### ISSUE THREAD

**Issue by aaroncox** [wharfkit/website#53]
Somewhere on the page (maybe right sidebar, below the table of contents) add a link to each documentation page that goes to the Github page for the document the user is reading. This will allow them to make edits to the documentation and submit a pull request with corrections.

An example from:

https://react.semantic-ui.com/elements/divider/

Notice in the top right the link to github for that specific page.

<img width="1286" alt="image" src="https://github.com/wharfkit/website/assets/677686/91df24c5-9f02-4208-90e2-637ccfeb962f">

**Comment by deansallinen** [comment]
Added in eb0d6eb099f5567fdae04e2e57c9920de49e0745
