### ISSUE TITLE
Split header margin into 50/50 margin/padding

### ISSUE THREAD

**Issue by aaroncox** [wharfkit/website#55]
https://dev.wharfkit-website.pages.dev/docs/antelope/api-client#usage

When using any of the anchors on the page, it scrolls exactly to where that content starts without any padding between the navigation and the header clicked on. 

It might be nice to move some of the margin in the header into a bit of padding, so it doesn't ram up against the navigation bar.

<img width="588" alt="image" src="https://github.com/wharfkit/website/assets/677686/e46dc11a-053f-4a15-9718-339e1394c49c">

**Comment by deansallinen** [comment]
Good catch. Probably a good candidate for `scroll-padding-top`

**Comment by deansallinen** [comment]
Fixed in b73e8e68a61e38709cdfba5ae46acc692bad4984
