### ISSUE TITLE
Word wrap in code blocks should be disabled

### ISSUE THREAD

**Issue by aaroncox** [wharfkit/website#56]
I don't think we want word wrap inside of code blocks like this, it should just overflow with a horizontal scroll to see the rest.

<img width="904" alt="image" src="https://github.com/wharfkit/website/assets/677686/093e57cb-659a-43e4-bd42-a16660664f56">

**Comment by deansallinen** [comment]
Fixed in [9d4f7e1](https://github.com/wharfkit/website/commit/9d4f7e13cc3662359af210e8a099c906c6822d88)
