### ISSUE TITLE
Header margins are a bit large

### ISSUE THREAD

**Issue by aaroncox** [wharfkit/website#58]
Just browsing through and IMO the margins above some of these headings are a bit large.

In this instance it's the margin above "Usage"

<img width="860" alt="image" src="https://github.com/wharfkit/website/assets/677686/c0ab3e4d-654d-41a9-a32d-7bebbb65062f">

**Comment by deansallinen** [comment]
The Figma design felt too tight, but I agree this does feel too loose. I'll tighten up the margins (for h2 especially)

**Comment by deansallinen** [comment]
Fixed in f341a836b8e1077e7e01b311a25b8ec90de64a4e
