### ISSUE TITLE
Frontmatter implementation

### ISSUE THREAD

**Issue by aaroncox** [wharfkit/website#59]
I think we do need an implementation of frontmatter in the documentation, all the navigation for Wharf is broken in the latest builds:

<img width="470" alt="image" src="https://github.com/wharfkit/website/assets/677686/cbb24741-8d1d-4559-b69f-8b1a0ea7291e">

**Comment by deansallinen** [comment]
Use cases
- Ordering articles within a section
- Showing and hiding articles (e.g. drafts)
- Ordering sections in sidebar
- Changing title and description for SEO

I've used https://github.com/wharfkit/website/blob/dev/src/routes/docs/importDocs.ts to solve both ordering and show/hide. Can move to frontmatter if needed, but this keeps all display preferences centralized. 

Will add the following options to frontmatter, specifically for manually overriding the SEO / social cards info on individual documentation pages.

- title
- description
- image

**Comment by deansallinen** [comment]
Added support for frontmatter in c95de01
