### ISSUE TITLE
Style active state for buttons and links

### ISSUE THREAD

**Issue by david-at-greymass** [wharfkit/website#71]

**Comment by Goodbyehorses** [comment]
![screenshot 1691671313](https://github.com/wharfkit/website/assets/216542/47283759-6304-4d27-be39-ffa00b072437)
Button bg color: #7BE7CE
Button hover bg color: #B2F2E1
button press bg color: #35CCAE

**Comment by Goodbyehorses** [comment]
![screenshot 1691687163](https://github.com/wharfkit/website/assets/216542/feadf1d8-b48d-44f7-8788-bcee036ab7b3)
light mode
default: #0A836F
hover: #1CB095
visited: #7A4578
dark mode
default: #35CCAE
hover: #B2F2E1
visited: #F8B9FF

**Comment by deansallinen** [comment]
Thanks @Goodbyehorses. Also looking for some guidance on active and focus states, unless we're okay with browser defaults:

**Comment by deansallinen** [comment]
[Kooha-2023-08-10-11-07-41.webm](https://github.com/wharfkit/website/assets/7519573/8df00882-3cdc-4661-9933-d0933f19a964)

**Comment by deansallinen** [comment]
![Screenshot_2023-08-10-10-57-39-52_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/wharfkit/website/assets/7519573/cb5f28f9-5adc-43ad-8b11-fb73d7fab639)

And in Chrome on Android we get this giant blue boxes

**Comment by deansallinen** [comment]
The blue on mobile Chrome can be removed entirely with `-webkit-tap-highlight-color: transparent;`

Do we want to replace the highlight color with an active/focused state?

**Comment by Goodbyehorses** [comment]
Lets try a better contrast for the focus,
![screenshot 1691748528](https://github.com/wharfkit/website/assets/216542/9c5d5302-9e0a-41f6-a966-37807f180fe9)
![screenshot 1691748501](https://github.com/wharfkit/website/assets/216542/7c2c5122-4b46-4fe1-ae07-3fb35ccb0a67)
#F78D1E 2px stroke
