### ISSUE TITLE
[Homepage] - Fix blank link

### ISSUE THREAD

**Issue by david-at-greymass** [wharfkit/website#82]

**Comment by david-at-greymass** [comment]
![Image](https://github.com/wharfkit/website/assets/139813631/4fb92f7b-f706-4d9e-a1ba-23d4f88b0ddb)

Needs to go somewhere… potentially https://docs.eosnetwork.com/docs/latest/quick-start/write-a-contract

**Comment by deansallinen** [comment]
Fixed in 51cd283bb5d38579ea4b36488bf431e4d5818e3c
