### ISSUE TITLE
[Docs/Guides] Cannot easily navigate to section on mobile using link in summary heading 

### ISSUE THREAD

**Issue by deansallinen** [wharfkit/website#84]
The link to the section index page is also the button to expand the details and all the section links.

![Screen Shot 2023-07-27 at 11 48 48](https://github.com/wharfkit/website/assets/7519573/7afe3cd9-b2b5-4981-9f54-93bfe34ff158)

**Comment by david-at-greymass** [comment]
@deansallinen do we need to fold all of the sub items in there? After jumping to the needed page it all folds again.
We can potentially utilize a slider with a sticky nav, like on mobile [HERE](https://eos.io/eosio-software-releases/)
