### ISSUE TITLE
Replace image here with stylized image showing web renderer

### ISSUE THREAD

**Issue by aaroncox** [wharfkit/website#93]
We can show an actual screenshot of the user interface (or multiple, with different states) instead of this generic image.

Maybe we can tile them or show multiple popups, first being a login, then a signing request, etc.

<img width="1483" alt="image" src="https://github.com/wharfkit/website/assets/677686/f6fe3528-f6a3-4d9f-b10d-9ef618e03e33">

**Comment by Goodbyehorses** [comment]
This could work
![screenshot 1690801882](https://github.com/wharfkit/website/assets/216542/2b93a87b-f87f-4f63-9848-0fd07587a10f)
![screenshot 1690802070](https://github.com/wharfkit/website/assets/216542/3759daab-c5c7-4f77-8b91-75b4ec7f7857)
