### ISSUE TITLE
Can't load pages where `published: false`

### ISSUE THREAD

**Issue by aaroncox** [wharfkit/website#96]
I thought we were changing it so all docs rendered, but they only showed on the sidebar when `published: true` was set 🤔 

If I'm misremembering, let me know. 

It's currently not working this way though: 

https://dev.wharfkit-website.pages.dev/docs/sessionkit/login

This page doesn't have `published: true` and cannot be loaded. As soon as I set `published: true` on the doc, I can load the page. I think that this `published` flag is still controlling both when it shows on the sidebar as well as if its published.

**UPDATE**: See comments below.

**Comment by aaroncox** [comment]
I have a lot of documentation coming up in the Session Kit area that I'm going to need this functional. There are a lot of pages I don't want to show on the sidebar, but do want to actually have rendered out and available for viewing if a link is clicked that goes directly to the page.

Here's kinda what I'm thinking at this point, let's add a `hidden: true` flag to the frontmatter that when set to true, prevents it from showing on the sidebar UNLESS its being searched for.

So given I have 3 pages:

- session, published: true
- login, published: true
- login-result: published: true, hidden: true

The sidebar from an HTML perspective would contain all 3 items, but the login-result entity would have some CSS property to hide it. 

Then, if I went to the search box and typed "login", the CSS property to hide it would be ignored, and the search bar would show both login and login-result.

**Comment by david-at-greymass** [comment]
@aaroncox It's possible to hide stuff from the nav bar, yet from SEO perspective hiding elements from page is frowned upon. I guess the bigger question here is do we need the link on the production site if the article isn't ready and needs additional work.

What I would recommend is to not render any links for **hidden: true** articles in production. And render all links in dev/local environments.

**Comment by aaroncox** [comment]
I'm not sure hiding this will have any impact on SEO since navigation elements are only really useful for spidering. We aren't hiding the content - we are just hiding the link on the menu unless someone searches for it. 

The pages should still be rendered and there are plenty of other links throughout the documentation that will reference it.

Example would be the LoginResult page:

https://kitdocs.wharfkit-website.pages.dev/docs/sessionkit/login-result

- This page should be rendered and available when the page is visited. 
- The link for this page SHOULD NOT be rendered in the navigation by default.
- The link for this page SHOULD show when searching using the sidebar search feature.
- This page is linked to from a number of other documents, like the first paragraph in https://kitdocs.wharfkit-website.pages.dev/docs/sessionkit/login

**Comment by deansallinen** [comment]
Here's the implementation I've come up with: https://github.com/wharfkit/website/pull/118

Existing behaviour (unchanged):
- Documentation articles will be rendered with `published: true`. With a falsy or undefined value, articles will not be rendered and are not accessible either directly or through sidebar navigation. This is essentially a "draft" stage for incomplete documentation.
- Articles with `published: true` will be rendered and accessible in the sidebar and by direct URL. This is the final stage for finalized and publicly available documentation.

New behaviour: 
- Articles with `published: true` and a new `hidden: true` flag will be rendered and accessible via direct URL, but not be added to the sidebar. They'll appear in the sidebar only when filtering with a matching query.  e.g. entering "login" will make the "LoginResult" article appear in the filtered results. 

Note: articles in a section without any existing published/visible articles will also need a published section index page, which can also be hidden. e.g. SessionKit.md with `slug: index` and `published: true` and `hidden: true`
